name: code

on:
  workflow_dispatch: 

jobs:
  clone_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Get latest go version
        id: version
        run: |
          echo ::set-output name=go_version::$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.version.outputs.go_version }}
          check-latest: true

      - name: code
        run: |
          git clone -b main https://github.com/maskedeken/NekoBoxForAndroid.git nb
          rm -f nb/release.keystore
          mv -f .github/release.keystore nb
          rm -f nb/buildScript/lib/core.sh
          mv -f .github/core.sh nb/buildScript/lib/
          cd nb/.github/workflows
          sed -i 's/find buildScript libcore\/\*.sh | xargs cat | sha1sum > golang_status/find . -type d -exec chmod 0755 {} + -o -type f -exec chmod 0755 {} + \&\& find buildScript libcore\/\*.sh | xargs cat | sha1sum > golang_status/g' release.yml
          sed -i 's/find buildScript libcore\/\*.sh | xargs cat | sha1sum > golang_status/find . -type d -exec chmod 0755 {} + -o -type f -exec chmod 0755 {} + \&\& find buildScript libcore\/\*.sh | xargs cat | sha1sum > golang_status/g' ci.yml
          cd ../..
          cd libcore
          sed -i 's/"with_wireguard"/"with_wireguard"\n    "with_shadowsocksr"/g' build.sh
          awk '{if(index($0, "// replace github.com/sagernet/sing =>") > 0) $0 = "replace github.com/sagernet/sing => ../../sing"}1' go.mod > temp_file && mv -f temp_file go.mod
          #awk '{if ($0 ~ /\/\/ replace github\.com\/sagernet\/sing-dns => \.\.\/\.\.\/sing-dns/) {print "// replace github.com/sagernet/sing-dns => ../../sing-dns"; print ""; print "replace github.com/sagernet/sing-quic => ../../sing-quic"} else {print $0}}' go.mod > temp_file && mv -f temp_file go.mod
          awk '{if(index($0, "replace github.com/sagernet/sing-box =>") > 0) $0 = "replace github.com/sagernet/sing-box => ../../sing-box"}1' go.mod > temp_file && mv -f temp_file go.mod
          awk '{if(index($0, "replace github.com/sagernet/sing-quic =>") > 0) $0 = "replace github.com/sagernet/sing-quic => ../../sing-quic"}1' go.mod > temp_file && mv -f temp_file go.mod
          #go mod tidy
          cd ../..
      
      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git checkout -b dev2.1
          rm -rf .github
          rm -f README.md
          cp -r nb/* .
          cp -r nb/.github .
          rm -rf nb
          git add .
          git commit -m "commit"
          git push --force origin dev2.1
